version: '2'
services: 
  mosquitto:
    build: ./mosquitto
    restart: always
    expose:
      - "1883"
      
  display:
    build: ./display
    privileged: true
    restart: always
    depends_on:
       - mosquitto

  joystick:
    build: ./joystick
    privileged: true
    restart: always
    depends_on:
       - mosquitto

  temperature:
    build: ./temperature
    privileged: true
    restart: always
    depends_on:
       - mosquitto

  nodered:
    build: ./nodered
    privileged: true
    restart: always
    ports:
       - 80:1880
    depends_on:
       - mosquitto
