version: '2'
services: 
  mosquitto:
    build: ./mosquitto
    restart: always
    expose:
      - "1883"
      
  display:
    build: ./display
    privileged: true
    restart: always
    depends_on:
       - mosquitto

  joystick:
    build: ./joystick
    privileged: true
    restart: always
    depends_on:
       - mosquitto
