version: '2'
services:
  sensehat:
   build: ./sensehat
   image: sensehat:base
   privileged: true
   restart: never

  display:
    build: ./display
    privileged: true
    restart: always
      - "5000:5000"

  joystick:
    build:
      depends_on: sensehat
      context: ./joystick
    privileged: true
    restart: always

  mosquitto:
    build: mosquitto
    restart: always
    expose:
      - "1883"
