version: '2'
services:
#  sensorhat:
#    build: ./sensehat
#    privileged: true
#    restart: always
#    ports:
#      - "5000:5000" 
  display:
    build: ./display
    image: display
    privileged: true
    restart: always
   
  display3:
    build: ./display3
    privileged: true
    restart: always

  joystick:
    build: ./joystick
    privileged: true
    restart: always

  mosquitto:
    build: mosquitto
    restart: always
    expose:
      - "1883"
