version: '3.0'
services:
  sensehat:
   build: 
    context: ./sensehat
    target: sensehat
    restart: never

  display:
    build: ./display
    privileged: true
    restart: always
      - "5000:5000"

  joystick:
    build:
      context: ./joystick
      cache-from: sensehat
    privileged: true
    restart: always

  mosquitto:
    build: mosquitto
    restart: always
    expose:
      - "1883"
