version: '2'
services:
  display:
    build: ./display
    image: display
    privileged: true
    restart: always

  joystick:
    build: ./joystick
    privileged: true
    restart: always

  mosquitto:
    build: mosquitto
    restart: always
    expose:
      - "1883"
