version: '2'
services:
#  sensorhat:
#    build: ./sensehat
#    privileged: true
#    restart: always
#    ports:
#      - "5000:5000" 
  display:
    build: ./display
    image: pgrabolosa/balena_test_display:latest
    privileged: true
    restart: always

  joystick:
    build: ./joystick
    image: pgrabolosa/balena_test_joystick:latest
    privileged: true
    restart: always

  mosquitto:
    build: ./mosquitto
    restart: always
    expose:
      - "1883"
